name: Growth

on:
  schedule:
    - cron: '30 7 * * *'
  
  workflow_dispatch:

jobs:
  growth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.0'

      - name: Depend install and start
        env:
          COOKIE: ${{ secrets.COOKIE }}
          MIAOTIXING_WEBHOOK: ${{ secrets.MIAOTIXING_WEBHOOK }}
        run: |
          npm install
          npm run start
